name: rick_and_morty_bloc
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  hydrated_bloc: ^8.0.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8
  rick_and_morty_repository:
    path: ../rick_and_morty_repository
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/characters.jpg
  fonts:
    - family: RickAndMotry
      fonts:
        - asset: assets/fonts/RickAndMotry.ttf

